# Generated by Django 3.2.9 on 2021-12-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['-created'], 'verbose_name': 'Метка', 'verbose_name_plural': 'Labels'},
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
