# Generated by Django 3.2.9 on 2021-12-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_auto_20211220_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Labels'},
        ),
    ]
