# Generated by Django 3.2.9 on 2021-12-20 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_alter_label_name'),
        ('statuses', '0002_alter_status_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20211220_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeling',
            name='task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='tasks.task'
                ),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='author', to=settings.AUTH_USER_MODEL
                ),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='executor', to=settings.AUTH_USER_MODEL
                ),
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(
                blank=True, related_name='labels',
                through='tasks.Labeling', to='labels.Label'
                ),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT,
                to='statuses.status'
                ),
        ),
    ]
