# Generated by Django 3.2.9 on 2021-12-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20211216_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
    ]
