# Generated by Django 3.2.9 on 2021-11-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={
                'ordering': ['-created'], 'verbose_name_plural': 'Statuses'
                },
        ),
    ]
